'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("apiPagesDesignBlock.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;div class=&quot;designBlockContainer api {{outerContainerClass}}&quot; style=&quot;{{styleHeight}}{{styleBackgroundImage}}&quot;&gt;
        '''   &lt;div class=&quot;{{contentContainerClass}}&quot;&gt;
        '''      &lt;div class=&quot;row&quot;&gt;
        '''		 {{#showPublish}}
        '''			&lt;div class=&quot;col-sm-12&quot;&gt;&lt;a class=&quot;btn btn-lg btn-block btn-success btn-primary&quot; href=&quot;?{{refreshQueryString}}&quot; role=&quot;button&quot;&gt;Publish&lt;/a&gt;&lt;/div&gt;
        '''		 {{/showPublish}}
        '''         {{#objectTypeList}}
        '''         &lt;div class=&quot;col-sm-6&quot;&gt;
        '''            {{{editTag}}}
        '''            &lt;br&gt;
        '''            &lt;h2 class=&quot;font-weight- [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ApiLayout() As String
            Get
                Return ResourceManager.GetString("ApiLayout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;div class=&quot;designBlockContainer blockContactForm {{#formSubmitted}}formSubmitted{{/formSubmitted}} {{outerContainerClass}}&quot; style=&quot;{{styleHeight}}{{styleBackgroundImage}}&quot;&gt;
        '''	&lt;div class=&quot;{{contentContainerClass}}&quot;&gt;
        '''		&lt;div class=&quot;blockContactFormInner&quot;&gt;
        '''			{{#formSubmitted}}
        '''			&lt;div class=&quot;blockContactFormThankYou db-row&quot;&gt;
        '''				&lt;div class=&quot;title-section width-80&quot;&gt;
        '''					&lt;h1&gt;{{thankYouTitle}}&lt;/h1&gt;
        '''					&lt;div&gt;{{{thankYouDescription}}}&lt;/div&gt;
        '''					&lt;div class=&quot;mt-2&quot;&gt;
        '''						&lt;button type=&quot;submit&quot; class=&quot;btn b [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ContactUsLayout() As String
            Get
                Return ResourceManager.GetString("ContactUsLayout", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
