'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Contensive.Addons.DesignBlockSample.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;div class=&quot;designBlockContainer blockOneColumn {{outerContainerClass}}&quot; style=&quot;{{styleHeight}}{{styleBackgroundImage}}&quot;&gt;
        '''	&lt;div class=&quot;{{contentContainerClass}}&quot;&gt;
        '''		&lt;div class=&quot;row&quot;&gt;
        '''			&lt;div class=&quot;col-lg-12&quot;&gt;{{{addonCol1}}}&lt;/div&gt;
        '''		&lt;/div&gt;
        '''	&lt;/div&gt;
        '''&lt;/div&gt;.
        '''</summary>
        Public ReadOnly Property OneColumnLayout() As String
            Get
                Return ResourceManager.GetString("OneColumnLayout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;div class=&quot;designBlockContainer blockTile {{outerContainerClass}}&quot; style=&quot;{{styleHeight}}{{styleBackgroundImage}}&quot;&gt;
        '''	&lt;div class=&quot;{{contentContainerClass}}&quot;&gt;
        '''		&lt;div class=&quot;blockTileInner&quot;&gt;
        '''			{{#ImageUrl}}
        '''				&lt;div class=&quot;blockTileImage&quot;&gt; 
        '''					{{#manageAspectRatio}}
        '''						&lt;div class=&quot;blockTileImageInner {{styleAspectRatio}}&quot; style=&quot;background-image: url({{ImageUrl}})&quot;&gt;&lt;/div&gt;
        '''					{{/manageAspectRatio}}
        '''					{{^manageAspectRatio}}
        '''						&lt;img src=&quot;{{ImageUrl}}&quot;&gt;
        '''					{{/manageAspectRatio}}
        '''				&lt;/d [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property SampleLayout() As String
            Get
                Return ResourceManager.GetString("SampleLayout", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
